### ISSUE TITLE
You might want to fork instead of re-upload

### ISSUE THREAD

**Issue by loucyx** [mayahq/cron#1]
Hi, folks!

I'm the creator and maintainer of the [library you re-uploaded and re-published](https://github.com/vangware/cron). The library will have a big update in the coming weeks (types, docs and so on). I recommend that instead of re-uploading and re-publishing this as your own, you use [the original package](https://npm.im/vangware/cron) or at least you fork the original project.

Cheers!

**Comment by shubham-root** [comment]
Looks like I silly blunder here. This repo is clone of https://github.com/nilaysavant/cron/tree/es5 and was intended for private use mostly as the original library was not working for our es5 target. But I totally see how it looks bad and we shall fix. Thanks for reporting. 

Also if the new update fixes the problems we were having, we won't even need to host this and I shall pull it down of here and npm.
